# Generated by Django 5.2.5 on 2025-08-11 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Drama", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Gaji_Post",
        ),
    ]
