# Generated by Django 5.2.5 on 2025-08-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Drama", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drama",
            name="image",
            field=models.ImageField(upload_to="Drama/"),
        ),
    ]
