# Generated by Django 5.2.5 on 2025-08-12 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Drama", "0004_alter_drama_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="drama",
            name="actors",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="drama",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="drama",
            name="director",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="drama",
            name="synopsis",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="drama",
            name="image",
            field=models.ImageField(upload_to="dramas/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="drama",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "drama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Drama.drama"
                    ),
                ),
            ],
        ),
    ]
