# Generated by Django 5.2.5 on 2025-08-12 10:44

import Drama.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Drama", "0005_drama_actors_drama_description_drama_director_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="drama",
            options={"verbose_name": "드라마", "verbose_name_plural": "드라마 목록"},
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(verbose_name="댓글 내용"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="drama",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="Drama.drama",
            ),
        ),
        migrations.AlterField(
            model_name="drama",
            name="actors",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="출연 배우"
            ),
        ),
        migrations.AlterField(
            model_name="drama",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="설명"),
        ),
        migrations.AlterField(
            model_name="drama",
            name="director",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="감독"
            ),
        ),
        migrations.AlterField(
            model_name="drama",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=Drama.models.get_upload_path,
                verbose_name="포스터",
            ),
        ),
        migrations.AlterField(
            model_name="drama",
            name="synopsis",
            field=models.TextField(blank=True, null=True, verbose_name="줄거리"),
        ),
        migrations.AlterField(
            model_name="drama",
            name="title",
            field=models.CharField(max_length=200, verbose_name="제목"),
        ),
    ]
