# Generated by Django 5.2.4 on 2025-08-08 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Toon', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gaji_Post',
        ),
    ]
