# Generated by Django 5.2.4 on 2025-08-08 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
