# Generated by Django 5.2.4 on 2025-07-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Book", "0002_post_update_at_alter_post_create_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="head_image",
            field=models.ImageField(blank=True, upload_to="Book/images/%Y/%m/%d/"),
        ),
    ]
