# Generated by Django 5.2.4 on 2025-07-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Book", "0003_post_head_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="file_upload",
            field=models.FileField(blank=True, upload_to="Book/files/%Y/%m/%d/"),
        ),
    ]
