# Generated by Django 5.2.4 on 2025-07-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Book", "0004_post_file_upload"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="hook_text",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
