# Generated by Django 5.2.4 on 2025-08-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Book", "0011_alter_comment_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="file_upload",
            field=models.FileField(
                blank=True, null=True, upload_to="Book/files/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="head_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="Book/images/%Y/%m/%d/"
            ),
        ),
    ]
