# Generated by Django 5.2.5 on 2025-08-12 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Book", "0012_alter_post_file_upload_alter_post_head_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="category",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="author",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="post",
        ),
        migrations.RemoveField(
            model_name="post",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
