# Generated by Django 5.2.4 on 2025-08-12 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0014_alter_post_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
