# Generated by Django 5.2.5 on 2025-08-08 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorygenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorytype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='Categorygenre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tools.categorygenre'),
        ),
        migrations.AddField(
            model_name='post',
            name='Categorytype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tools.categorytype'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
