# Generated by Django 5.2.5 on 2025-08-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tools', '0002_categorygenre_categorytype_remove_post_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorygenre',
            name='slug',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='categorytype',
            name='slug',
            field=models.CharField(unique=True),
        ),
    ]
