# Generated by Django 5.2.5 on 2025-08-11 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tools', '0003_alter_categorygenre_slug_alter_categorytype_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='highlights/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlight_images', to='Tools.post')),
            ],
        ),
    ]
