# Generated by Django 5.2.5 on 2025-08-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tools', '0004_highlightimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlightimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
