# Generated by Django 5.2.5 on 2025-08-11 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tools', '0005_alter_highlightimage_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uploaded_image',
        ),
    ]
