# Generated by Django 5.2.5 on 2025-08-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tools', '0006_remove_post_uploaded_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
