# Generated by Django 5.2.4 on 2025-08-13 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tools', '0010_cast'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cast',
        ),
    ]
